name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'eu-north-1'
  EC2_HOST: '13.53.186.38'
  EC2_USERNAME: 'ubuntu'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Check JDK version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Install JDK if not available
        run: |
          if ! command -v java &> /dev/null; then
            sudo apt-get install -y openjdk-17-jdk
          fi

      - name: Install Maven if not available
        run: |
          if ! command -v mvn &> /dev/null; then
            sudo apt-get install -y maven
          fi

      - name: Build with Maven
        run: |
          cd demo
          mvn clean install -f pom.xml

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd deploy
            mvn spring-boot:run
