name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'eu-north-1'
  EC2_HOST: '13.53.186.38'
  EC2_USERNAME: 'ubuntu'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permissions to mvnw script
        run: chmod +x demo/mvnw

      - name: Install dependencies and build
        run: |
          cd demo
          ./mvnw clean install -Dmaven.repo.local=./.m2/repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd InstagramClone
            ./mvnw spring-boot:run -Dmaven.repo.local=./.m2/repository
