name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: sudo docker build -t my-spring-app .

      - name: Stop running containers
        run: |
          # Stop and remove existing containers with the same name
          sudo docker stop my-spring-container || true
          sudo docker rm my-spring-container || true

      - name: Start new container
        run: sudo docker run -d --name my-spring-container -p 8080:8080 my-spring-app
