name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Maven is installed
        run: |
          mvn --version
          echo "Maven is already installed"
        continue-on-error: true

      - name: Install Maven
        if: ${{ failure() }}
        run: |
          sudo apt-get install -y maven

      - name: Check if Java is installed
        run: |
          java -version
          echo "Java is already installed"
        continue-on-error: true

      - name: Install Java
        if: ${{ failure() }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y openjdk-17-jdk

      - name: Build with Maven
        run: |
          cd demo
          mvn clean install -f pom.xml

      - name: Stop the systemd service
        run: |
          sudo systemctl stop my-spring-app

      - name: Clean deploy folder
        run: |
          rm -rf deploy

      - name: Copy JAR files to deploy folder
        run: |
          mkdir deploy
          cp demo/target/*.jar deploy/

      - name: Check if systemd service file exists
        id: check_service_file
        run: |
          if [ -f /etc/systemd/system/my-spring-app.service ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create systemd service file
        run: |
          if [[ "${{ steps.check_service_file.outputs.exists }}" == "false" ]]; then
            jar_path=$(find deploy -name '*.jar' -type f)
            if [[ -n $jar_path ]]; then
              echo "[Unit]
              Description=My Spring Boot Application
              After=syslog.target

              [Service]
              User=spring
              ExecStart=/usr/bin/java -jar $jar_path
              Restart=always
              SuccessExitStatus=143

              [Install]
              WantedBy=multi-user.target" | sudo tee /etc/systemd/system/my-spring-app.service
            else
              echo "No JAR file found in the deploy directory."
              exit 1
            fi
          else
            echo "Systemd service file already exists. Skipping creation."

      - name: Enable and start the systemd service
        run: |
          sudo systemctl enable my-spring-app

      - name: Start the systemd service
        run: |
          sudo systemctl start my-spring-app
